M48
; DRILL file {KiCad (6.0.10)} date Sun Apr 23 12:08:17 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-23T12:08:17+05:45
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
%
G90
G05
T1
X5.4Y-3.9
T2
X4.8Y-4.2
X5.3Y-4.2
T3
X4.2071Y-4.0968
X4.2071Y-4.1968
T0
M30
